// Membership Plan Features Constants
// These constants represent the semantic abbreviated global variables for all features

export const FEATURES = {
  // Check Intervals
  CHECK_INTERVAL_5MIN: 'CHECK_INTERVAL_5MIN',
  CHECK_INTERVAL_1MIN: 'CHECK_INTERVAL_1MIN',
  CHECK_INTERVAL_30SEC: 'CHECK_INTERVAL_30SEC',
  
  // AI Diagnostics
  AI_DIAGNOSTICS_BASIC: 'AI_DIAGNOSTICS_BASIC',
  AI_DIAGNOSTICS_ADVANCED: 'AI_DIAGNOSTICS_ADVANCED',
  AI_DIAGNOSTICS_ENTERPRISE: 'AI_DIAGNOSTICS_ENTERPRISE',
  
  // Alert Types
  ALERTS_EMAIL: 'ALERTS_EMAIL',
  ALERTS_SLACK: 'ALERTS_SLACK',
  ALERTS_DISCORD: 'ALERTS_DISCORD',
  
  // Advanced Features
  PREDICTIVE_MONITORING: 'PREDICTIVE_MONITORING',
  PREDICTIVE_MONITORING_ADVANCED: 'PREDICTIVE_MONITORING_ADVANCED',
  REPORT_PDF: 'REPORT_PDF',
  DNS_SSL_MONITORING: 'DNS_SSL_MONITORING',
  
  // Guarantees
  LIFETIME_GUARANTEE: 'LIFETIME GUARANTEE',
} as const;

// Feature descriptions mapping
export const FEATURE_DESCRIPTIONS = {
  [FEATURES.CHECK_INTERVAL_5MIN]: '5-minute checks',
  [FEATURES.CHECK_INTERVAL_1MIN]: '1-minute checks',
  [FEATURES.CHECK_INTERVAL_30SEC]: '30-second checks',
  
  [FEATURES.AI_DIAGNOSTICS_BASIC]: 'Basic AI diagnostics',
  [FEATURES.AI_DIAGNOSTICS_ADVANCED]: 'Advanced AI diagnostics',
  [FEATURES.AI_DIAGNOSTICS_ENTERPRISE]: 'Enterprise AI diagnostics',
  
  [FEATURES.ALERTS_EMAIL]: 'Email alerts',
  [FEATURES.ALERTS_SLACK]: 'Slack alerts',
  [FEATURES.ALERTS_DISCORD]: 'Discord alerts',
  
  [FEATURES.PREDICTIVE_MONITORING]: 'Predictive monitoring',
  [FEATURES.PREDICTIVE_MONITORING_ADVANCED]: 'Advanced predictive monitoring',
  [FEATURES.REPORT_PDF]: 'PDF reports',
  [FEATURES.DNS_SSL_MONITORING]: 'DNS & SSL monitoring',
  
  [FEATURES.LIFETIME_GUARANTEE]: 'Lifetime guarantee',
} as const;

// Feature categories for organization
export const FEATURE_CATEGORIES = {
  MONITORING: [
    FEATURES.CHECK_INTERVAL_5MIN,
    FEATURES.CHECK_INTERVAL_1MIN,
    FEATURES.CHECK_INTERVAL_30SEC,
    FEATURES.DNS_SSL_MONITORING,
  ],
  INTELLIGENCE: [
    FEATURES.AI_DIAGNOSTICS_BASIC,
    FEATURES.AI_DIAGNOSTICS_ADVANCED,
    FEATURES.AI_DIAGNOSTICS_ENTERPRISE,
    FEATURES.PREDICTIVE_MONITORING,
    FEATURES.PREDICTIVE_MONITORING_ADVANCED,
  ],
  NOTIFICATIONS: [
    FEATURES.ALERTS_EMAIL,
    FEATURES.ALERTS_SLACK,
    FEATURES.ALERTS_DISCORD,
  ],
  REPORTING: [
    FEATURES.REPORT_PDF,
  ],
  GUARANTEES: [
    FEATURES.LIFETIME_GUARANTEE,
  ],
} as const;

// Type definitions
export type FeatureKey = typeof FEATURES[keyof typeof FEATURES];
export type FeatureDescription = typeof FEATURE_DESCRIPTIONS[FeatureKey];
export type FeatureCategory = keyof typeof FEATURE_CATEGORIES; 