// Membership Plan Features Constants
// These constants represent the semantic abbreviated global variables for all features

export const FEATURES = {
  // Website Monitoring Limits
  MONITORED_WEBSITES_10: 'MONITORED_WEBSITES_10',
  MONITORED_WEBSITES_50: 'MONITORED_WEBSITES_50',
  MONITORED_WEBSITES_200: 'MONITORED_WEBSITES_200',
  
  // Check Intervals
  CHECK_INTERVAL_5MIN: 'CHECK_INTERVAL_5MIN',
  CHECK_INTERVAL_1MIN: 'CHECK_INTERVAL_1MIN',
  CHECK_INTERVAL_30SEC: 'CHECK_INTERVAL_30SEC',
  
  // AI Diagnostics
  AI_DIAGNOSTICS_BASIC: 'AI_DIAGNOSTICS_BASIC',
  AI_DIAGNOSTICS_ADVANCED: 'AI_DIAGNOSTICS_ADVANCED',
  AI_DIAGNOSTICS_PREMIUM: 'AI_DIAGNOSTICS_PREMIUM',
  
  // Alert Types
  ALERTS_EMAIL: 'ALERTS_EMAIL',
  ALERTS_SLACK: 'ALERTS_SLACK',
  ALERTS_TELEGRAM: 'ALERTS_TELEGRAM',
  ALERTS_DISCORD: 'ALERTS_DISCORD',
  ALERTS_WEBHOOK: 'ALERTS_WEBHOOK',
  ALERTS_PUSH_NOTIFICATION: 'ALERTS_PUSH_NOTIFICATION',
  
  // White-label Features
  WHITELABEL_DASHBOARD: 'WHITELABEL_DASHBOARD',
  WHITELABEL_FULL: 'WHITELABEL_FULL',
  WHITELABEL_COMPLETE: 'WHITELABEL_COMPLETE',
  
  // Client Management
  CLIENT_SUBACCOUNTS: 'CLIENT_SUBACCOUNTS',
  MULTI_USER_LOGINS: 'MULTI_USER_LOGINS',
  
  // API & Integration
  API_ACCESS: 'API_ACCESS',
  WEBHOOK_ACCESS: 'WEBHOOK_ACCESS',
  
  // Advanced Features
  PREDICTIVE_MONITORING: 'PREDICTIVE_MONITORING',
  BRANDED_PDF_REPORTS: 'BRANDED_PDF_REPORTS',
} as const;

// Feature descriptions mapping
export const FEATURE_DESCRIPTIONS = {
  [FEATURES.MONITORED_WEBSITES_10]: '10 monitored websites',
  [FEATURES.MONITORED_WEBSITES_50]: '50 monitored websites',
  [FEATURES.MONITORED_WEBSITES_200]: '200 monitored websites',
  
  [FEATURES.CHECK_INTERVAL_5MIN]: '5-minute checks',
  [FEATURES.CHECK_INTERVAL_1MIN]: '1-minute checks',
  [FEATURES.CHECK_INTERVAL_30SEC]: '30-second checks',
  
  [FEATURES.AI_DIAGNOSTICS_BASIC]: 'Basic AI diagnostics',
  [FEATURES.AI_DIAGNOSTICS_ADVANCED]: 'Advanced AI diagnostics',
  [FEATURES.AI_DIAGNOSTICS_PREMIUM]: 'Premium AI diagnostics',
  
  [FEATURES.ALERTS_EMAIL]: 'Email alerts',
  [FEATURES.ALERTS_SLACK]: 'Slack alerts',
  [FEATURES.ALERTS_TELEGRAM]: 'Telegram alerts',
  [FEATURES.ALERTS_DISCORD]: 'Discord alerts',
  [FEATURES.ALERTS_WEBHOOK]: 'Webhook alerts',
  [FEATURES.ALERTS_PUSH_NOTIFICATION]: 'Push notifications',
  
  [FEATURES.WHITELABEL_DASHBOARD]: 'White-label dashboard',
  [FEATURES.WHITELABEL_FULL]: 'Full white-label solution',
  [FEATURES.WHITELABEL_COMPLETE]: 'Complete white-label',
  
  [FEATURES.CLIENT_SUBACCOUNTS]: 'Client sub-accounts',
  [FEATURES.MULTI_USER_LOGINS]: 'Multi-user logins',
  
  [FEATURES.API_ACCESS]: 'API access',
  [FEATURES.WEBHOOK_ACCESS]: 'Webhook access',
  
  [FEATURES.PREDICTIVE_MONITORING]: 'Predictive monitoring',
  [FEATURES.BRANDED_PDF_REPORTS]: 'Branded PDF reports',
} as const;

// Feature categories for organization
export const FEATURE_CATEGORIES = {
  MONITORING: [
    FEATURES.MONITORED_WEBSITES_10,
    FEATURES.MONITORED_WEBSITES_50,
    FEATURES.MONITORED_WEBSITES_200,
    FEATURES.CHECK_INTERVAL_5MIN,
    FEATURES.CHECK_INTERVAL_1MIN,
    FEATURES.CHECK_INTERVAL_30SEC,
  ],
  INTELLIGENCE: [
    FEATURES.AI_DIAGNOSTICS_BASIC,
    FEATURES.AI_DIAGNOSTICS_ADVANCED,
    FEATURES.AI_DIAGNOSTICS_PREMIUM,
    FEATURES.PREDICTIVE_MONITORING,
  ],
  NOTIFICATIONS: [
    FEATURES.ALERTS_EMAIL,
    FEATURES.ALERTS_SLACK,
    FEATURES.ALERTS_TELEGRAM,
    FEATURES.ALERTS_DISCORD,
    FEATURES.ALERTS_WEBHOOK,
    FEATURES.ALERTS_PUSH_NOTIFICATION,
  ],
  BRANDING: [
    FEATURES.WHITELABEL_DASHBOARD,
    FEATURES.WHITELABEL_FULL,
    FEATURES.WHITELABEL_COMPLETE,
    FEATURES.BRANDED_PDF_REPORTS,
  ],
  MANAGEMENT: [
    FEATURES.CLIENT_SUBACCOUNTS,
    FEATURES.MULTI_USER_LOGINS,
  ],
  INTEGRATION: [
    FEATURES.API_ACCESS,
    FEATURES.WEBHOOK_ACCESS,
  ],
} as const;

// Type definitions
export type FeatureKey = typeof FEATURES[keyof typeof FEATURES];
export type FeatureDescription = typeof FEATURE_DESCRIPTIONS[FeatureKey];
export type FeatureCategory = keyof typeof FEATURE_CATEGORIES; 